version: '3.7'

services:

  todo-vue:
    container_name: todo-vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'